code: 0
swordName: copper sword
swordSpecialSword: 0
swordSpecialPower: 1
candiesNbrOwned: 317
candiesNbrThrown: 20
candiesNbrEaten: 165
candiesNbrTotal: 2132
candiesCandiesPerSecond: 1
candiesConverterActivated: 0
cauldronBookPage: 0
cauldronCandies: 0
cauldronLollipops: 0
chocolateBarsNbrOwned: 0
farmLollipopsPlanted: 23
farmCurrentFlagIndex: 0
farmPlantingButtonsStep: 2
forgeStep: 0
shopLollipopsButtonsShown: 1
shopShown: 1
shopTicklingStep: 0
shopClickingOnLollipopStep: 0
hutStep: 0
hutSpeech: 
inventoryMagicianHatLetter: 
lollipopsNbrOwned: 0
lollipopsNbrInStock: 137
lollipopsNbrBought: 23
mainNbrOfSecondsSinceLastMinInterval: 25
mainNbrOfSecondsSinceLastHourInterval: 2125
mainNbrOfSecondsSinceLastDayInterval: 2125
mountGoblinBasicChestProbability: 50
peacefulForestBasicChestProbability: 100
peacefulForestPoniesEncountered: 0
objectsHaveObjectKey: 1
objectsHaveObjectHutMap: 0
objectsHaveObjectWellMap: 0
objectsHaveObjectSwampMap: 0
objectsHaveObjectBoots: 0
objectsHaveObjectMagicianHat: 0
objectsHaveObjectPinkRing: 0
objectsHaveObjectForgeMap: 0
objectsHaveObjectCandiesConverter: 0
objectsHaveObjectPlateArmour: 0
objectsHaveObjectCauldron: 0
objectsHaveObjectMagicalHorn: 0
objectsHaveObjectHornOfPlenty: 0
objectsHaveObjectOldAmulet: 0
potionsShownHealth: 0
potionsShownEscape: 0
potionsShownBerserk: 0
potionsShownFireScroll: 0
potionsShownAcidRainScroll: 0
potionsShownTeleportScroll: 0
potionsShownEarthquakeScroll: 0
potionsShownImpInvocationScroll: 0
potionsShownMajorHealth: 0
potionsShownInvulnerability: 0
potionsShownTurtle: 0
potionsShownJelly: 0
potionsShownSeed: 0
potionsShownCloning: 0
potionsShownSuperman: 0
potionsShownGmooh: 0
potionsNbrOwnedHealth: 0
potionsNbrOwnedEscape: 0
potionsNbrOwnedBerserk: 0
potionsNbrOwnedFireScroll: 0
potionsNbrOwnedAcidRainScroll: 0
potionsNbrOwnedTeleportScroll: 0
potionsNbrOwnedEarthquakeScroll: 0
potionsNbrOwnedImpInvocationScroll: 0
potionsNbrOwnedMajorHealth: 0
potionsNbrOwnedInvulnerability: 0
potionsNbrOwnedTurtle: 0
potionsNbrOwnedJelly: 0
potionsNbrOwnedSeed: 0
potionsNbrOwnedCloning: 0
potionsNbrOwnedSuperman: 0
potionsNbrOwnedGmooh: 0
questMaxLandOrder: 1
questTiredTime: 0
spellsFasterCandiesFibo1: 1
spellsFasterCandiesFibo2: 2
swampStep: 0
tabsAnimation: slide
wishingWellSpeech: 
wishingWellStep: 0
yourselfCanSurpass: 0
developperComputerWon: 0